// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CollectionsColumns holds the columns for the "collections" table.
	CollectionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// CollectionsTable holds the schema information for the "collections" table.
	CollectionsTable = &schema.Table{
		Name:        "collections",
		Columns:     CollectionsColumns,
		PrimaryKey:  []*schema.Column{CollectionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// RecsColumns holds the columns for the "recs" table.
	RecsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "type", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "metadata", Type: field.TypeJSON},
	}
	// RecsTable holds the schema information for the "recs" table.
	RecsTable = &schema.Table{
		Name:        "recs",
		Columns:     RecsColumns,
		PrimaryKey:  []*schema.Column{RecsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CollectionsTable,
		RecsTable,
	}
)

func init() {
}
