// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"log"

	"github.com/google/uuid"
	"github.com/ugent-library/momo/ent/migrate"

	"github.com/ugent-library/momo/ent/rec"
	"github.com/ugent-library/momo/ent/representation"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Rec is the client for interacting with the Rec builders.
	Rec *RecClient
	// Representation is the client for interacting with the Representation builders.
	Representation *RepresentationClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Rec = NewRecClient(c.config)
	c.Representation = NewRepresentationClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:            ctx,
		config:         cfg,
		Rec:            NewRecClient(cfg),
		Representation: NewRepresentationClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		config:         cfg,
		Rec:            NewRecClient(cfg),
		Representation: NewRepresentationClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Rec.
//		Query().
//		Count(ctx)
//
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Rec.Use(hooks...)
	c.Representation.Use(hooks...)
}

// RecClient is a client for the Rec schema.
type RecClient struct {
	config
}

// NewRecClient returns a client for the Rec from the given config.
func NewRecClient(c config) *RecClient {
	return &RecClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `rec.Hooks(f(g(h())))`.
func (c *RecClient) Use(hooks ...Hook) {
	c.hooks.Rec = append(c.hooks.Rec, hooks...)
}

// Create returns a create builder for Rec.
func (c *RecClient) Create() *RecCreate {
	mutation := newRecMutation(c.config, OpCreate)
	return &RecCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Rec entities.
func (c *RecClient) CreateBulk(builders ...*RecCreate) *RecCreateBulk {
	return &RecCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Rec.
func (c *RecClient) Update() *RecUpdate {
	mutation := newRecMutation(c.config, OpUpdate)
	return &RecUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *RecClient) UpdateOne(r *Rec) *RecUpdateOne {
	mutation := newRecMutation(c.config, OpUpdateOne, withRec(r))
	return &RecUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *RecClient) UpdateOneID(id uuid.UUID) *RecUpdateOne {
	mutation := newRecMutation(c.config, OpUpdateOne, withRecID(id))
	return &RecUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Rec.
func (c *RecClient) Delete() *RecDelete {
	mutation := newRecMutation(c.config, OpDelete)
	return &RecDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *RecClient) DeleteOne(r *Rec) *RecDeleteOne {
	return c.DeleteOneID(r.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *RecClient) DeleteOneID(id uuid.UUID) *RecDeleteOne {
	builder := c.Delete().Where(rec.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &RecDeleteOne{builder}
}

// Query returns a query builder for Rec.
func (c *RecClient) Query() *RecQuery {
	return &RecQuery{config: c.config}
}

// Get returns a Rec entity by its id.
func (c *RecClient) Get(ctx context.Context, id uuid.UUID) (*Rec, error) {
	return c.Query().Where(rec.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *RecClient) GetX(ctx context.Context, id uuid.UUID) *Rec {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryRepresentations queries the representations edge of a Rec.
func (c *RecClient) QueryRepresentations(r *Rec) *RepresentationQuery {
	query := &RepresentationQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := r.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(rec.Table, rec.FieldID, id),
			sqlgraph.To(representation.Table, representation.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, rec.RepresentationsTable, rec.RepresentationsColumn),
		)
		fromV = sqlgraph.Neighbors(r.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *RecClient) Hooks() []Hook {
	return c.hooks.Rec
}

// RepresentationClient is a client for the Representation schema.
type RepresentationClient struct {
	config
}

// NewRepresentationClient returns a client for the Representation from the given config.
func NewRepresentationClient(c config) *RepresentationClient {
	return &RepresentationClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `representation.Hooks(f(g(h())))`.
func (c *RepresentationClient) Use(hooks ...Hook) {
	c.hooks.Representation = append(c.hooks.Representation, hooks...)
}

// Create returns a create builder for Representation.
func (c *RepresentationClient) Create() *RepresentationCreate {
	mutation := newRepresentationMutation(c.config, OpCreate)
	return &RepresentationCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Representation entities.
func (c *RepresentationClient) CreateBulk(builders ...*RepresentationCreate) *RepresentationCreateBulk {
	return &RepresentationCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Representation.
func (c *RepresentationClient) Update() *RepresentationUpdate {
	mutation := newRepresentationMutation(c.config, OpUpdate)
	return &RepresentationUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *RepresentationClient) UpdateOne(r *Representation) *RepresentationUpdateOne {
	mutation := newRepresentationMutation(c.config, OpUpdateOne, withRepresentation(r))
	return &RepresentationUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *RepresentationClient) UpdateOneID(id uuid.UUID) *RepresentationUpdateOne {
	mutation := newRepresentationMutation(c.config, OpUpdateOne, withRepresentationID(id))
	return &RepresentationUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Representation.
func (c *RepresentationClient) Delete() *RepresentationDelete {
	mutation := newRepresentationMutation(c.config, OpDelete)
	return &RepresentationDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *RepresentationClient) DeleteOne(r *Representation) *RepresentationDeleteOne {
	return c.DeleteOneID(r.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *RepresentationClient) DeleteOneID(id uuid.UUID) *RepresentationDeleteOne {
	builder := c.Delete().Where(representation.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &RepresentationDeleteOne{builder}
}

// Query returns a query builder for Representation.
func (c *RepresentationClient) Query() *RepresentationQuery {
	return &RepresentationQuery{config: c.config}
}

// Get returns a Representation entity by its id.
func (c *RepresentationClient) Get(ctx context.Context, id uuid.UUID) (*Representation, error) {
	return c.Query().Where(representation.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *RepresentationClient) GetX(ctx context.Context, id uuid.UUID) *Representation {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryRec queries the rec edge of a Representation.
func (c *RepresentationClient) QueryRec(r *Representation) *RecQuery {
	query := &RecQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := r.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(representation.Table, representation.FieldID, id),
			sqlgraph.To(rec.Table, rec.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, representation.RecTable, representation.RecColumn),
		)
		fromV = sqlgraph.Neighbors(r.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *RepresentationClient) Hooks() []Hook {
	return c.hooks.Representation
}
