// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/ugent-library/momo/ent/predicate"
	"github.com/ugent-library/momo/ent/rec"
	"github.com/ugent-library/momo/ent/representation"
)

// RepresentationUpdate is the builder for updating Representation entities.
type RepresentationUpdate struct {
	config
	hooks    []Hook
	mutation *RepresentationMutation
}

// Where adds a new predicate for the RepresentationUpdate builder.
func (ru *RepresentationUpdate) Where(ps ...predicate.Representation) *RepresentationUpdate {
	ru.mutation.predicates = append(ru.mutation.predicates, ps...)
	return ru
}

// SetFormat sets the "format" field.
func (ru *RepresentationUpdate) SetFormat(s string) *RepresentationUpdate {
	ru.mutation.SetFormat(s)
	return ru
}

// SetData sets the "data" field.
func (ru *RepresentationUpdate) SetData(b []byte) *RepresentationUpdate {
	ru.mutation.SetData(b)
	return ru
}

// SetRecID sets the "rec" edge to the Rec entity by ID.
func (ru *RepresentationUpdate) SetRecID(id uuid.UUID) *RepresentationUpdate {
	ru.mutation.SetRecID(id)
	return ru
}

// SetNillableRecID sets the "rec" edge to the Rec entity by ID if the given value is not nil.
func (ru *RepresentationUpdate) SetNillableRecID(id *uuid.UUID) *RepresentationUpdate {
	if id != nil {
		ru = ru.SetRecID(*id)
	}
	return ru
}

// SetRec sets the "rec" edge to the Rec entity.
func (ru *RepresentationUpdate) SetRec(r *Rec) *RepresentationUpdate {
	return ru.SetRecID(r.ID)
}

// Mutation returns the RepresentationMutation object of the builder.
func (ru *RepresentationUpdate) Mutation() *RepresentationMutation {
	return ru.mutation
}

// ClearRec clears the "rec" edge to the Rec entity.
func (ru *RepresentationUpdate) ClearRec() *RepresentationUpdate {
	ru.mutation.ClearRec()
	return ru
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ru *RepresentationUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	ru.defaults()
	if len(ru.hooks) == 0 {
		if err = ru.check(); err != nil {
			return 0, err
		}
		affected, err = ru.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*RepresentationMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = ru.check(); err != nil {
				return 0, err
			}
			ru.mutation = mutation
			affected, err = ru.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(ru.hooks) - 1; i >= 0; i-- {
			mut = ru.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ru.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (ru *RepresentationUpdate) SaveX(ctx context.Context) int {
	affected, err := ru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ru *RepresentationUpdate) Exec(ctx context.Context) error {
	_, err := ru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ru *RepresentationUpdate) ExecX(ctx context.Context) {
	if err := ru.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ru *RepresentationUpdate) defaults() {
	if _, ok := ru.mutation.UpdatedAt(); !ok {
		v := representation.UpdateDefaultUpdatedAt()
		ru.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ru *RepresentationUpdate) check() error {
	if v, ok := ru.mutation.Format(); ok {
		if err := representation.FormatValidator(v); err != nil {
			return &ValidationError{Name: "format", err: fmt.Errorf("ent: validator failed for field \"format\": %w", err)}
		}
	}
	return nil
}

func (ru *RepresentationUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   representation.Table,
			Columns: representation.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: representation.FieldID,
			},
		},
	}
	if ps := ru.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ru.mutation.Format(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: representation.FieldFormat,
		})
	}
	if value, ok := ru.mutation.Data(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeBytes,
			Value:  value,
			Column: representation.FieldData,
		})
	}
	if value, ok := ru.mutation.UpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: representation.FieldUpdatedAt,
		})
	}
	if ru.mutation.RecCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   representation.RecTable,
			Columns: []string{representation.RecColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: rec.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ru.mutation.RecIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   representation.RecTable,
			Columns: []string{representation.RecColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: rec.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{representation.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// RepresentationUpdateOne is the builder for updating a single Representation entity.
type RepresentationUpdateOne struct {
	config
	hooks    []Hook
	mutation *RepresentationMutation
}

// SetFormat sets the "format" field.
func (ruo *RepresentationUpdateOne) SetFormat(s string) *RepresentationUpdateOne {
	ruo.mutation.SetFormat(s)
	return ruo
}

// SetData sets the "data" field.
func (ruo *RepresentationUpdateOne) SetData(b []byte) *RepresentationUpdateOne {
	ruo.mutation.SetData(b)
	return ruo
}

// SetRecID sets the "rec" edge to the Rec entity by ID.
func (ruo *RepresentationUpdateOne) SetRecID(id uuid.UUID) *RepresentationUpdateOne {
	ruo.mutation.SetRecID(id)
	return ruo
}

// SetNillableRecID sets the "rec" edge to the Rec entity by ID if the given value is not nil.
func (ruo *RepresentationUpdateOne) SetNillableRecID(id *uuid.UUID) *RepresentationUpdateOne {
	if id != nil {
		ruo = ruo.SetRecID(*id)
	}
	return ruo
}

// SetRec sets the "rec" edge to the Rec entity.
func (ruo *RepresentationUpdateOne) SetRec(r *Rec) *RepresentationUpdateOne {
	return ruo.SetRecID(r.ID)
}

// Mutation returns the RepresentationMutation object of the builder.
func (ruo *RepresentationUpdateOne) Mutation() *RepresentationMutation {
	return ruo.mutation
}

// ClearRec clears the "rec" edge to the Rec entity.
func (ruo *RepresentationUpdateOne) ClearRec() *RepresentationUpdateOne {
	ruo.mutation.ClearRec()
	return ruo
}

// Save executes the query and returns the updated Representation entity.
func (ruo *RepresentationUpdateOne) Save(ctx context.Context) (*Representation, error) {
	var (
		err  error
		node *Representation
	)
	ruo.defaults()
	if len(ruo.hooks) == 0 {
		if err = ruo.check(); err != nil {
			return nil, err
		}
		node, err = ruo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*RepresentationMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = ruo.check(); err != nil {
				return nil, err
			}
			ruo.mutation = mutation
			node, err = ruo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(ruo.hooks) - 1; i >= 0; i-- {
			mut = ruo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ruo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (ruo *RepresentationUpdateOne) SaveX(ctx context.Context) *Representation {
	node, err := ruo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ruo *RepresentationUpdateOne) Exec(ctx context.Context) error {
	_, err := ruo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ruo *RepresentationUpdateOne) ExecX(ctx context.Context) {
	if err := ruo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ruo *RepresentationUpdateOne) defaults() {
	if _, ok := ruo.mutation.UpdatedAt(); !ok {
		v := representation.UpdateDefaultUpdatedAt()
		ruo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ruo *RepresentationUpdateOne) check() error {
	if v, ok := ruo.mutation.Format(); ok {
		if err := representation.FormatValidator(v); err != nil {
			return &ValidationError{Name: "format", err: fmt.Errorf("ent: validator failed for field \"format\": %w", err)}
		}
	}
	return nil
}

func (ruo *RepresentationUpdateOne) sqlSave(ctx context.Context) (_node *Representation, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   representation.Table,
			Columns: representation.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: representation.FieldID,
			},
		},
	}
	id, ok := ruo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Representation.ID for update")}
	}
	_spec.Node.ID.Value = id
	if ps := ruo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ruo.mutation.Format(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: representation.FieldFormat,
		})
	}
	if value, ok := ruo.mutation.Data(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeBytes,
			Value:  value,
			Column: representation.FieldData,
		})
	}
	if value, ok := ruo.mutation.UpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: representation.FieldUpdatedAt,
		})
	}
	if ruo.mutation.RecCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   representation.RecTable,
			Columns: []string{representation.RecColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: rec.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ruo.mutation.RecIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   representation.RecTable,
			Columns: []string{representation.RecColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: rec.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Representation{config: ruo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ruo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{representation.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return _node, nil
}
