// Code generated by entc, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/google/uuid"
	"github.com/ugent-library/momo/internal/storage/sql/ent/collection"
	"github.com/ugent-library/momo/internal/storage/sql/ent/rec"
	"github.com/ugent-library/momo/internal/storage/sql/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	collectionFields := schema.Collection{}.Fields()
	_ = collectionFields
	// collectionDescName is the schema descriptor for name field.
	collectionDescName := collectionFields[1].Descriptor()
	// collection.NameValidator is a validator for the "name" field. It is called by the builders before save.
	collection.NameValidator = collectionDescName.Validators[0].(func(string) error)
	// collectionDescCreatedAt is the schema descriptor for created_at field.
	collectionDescCreatedAt := collectionFields[2].Descriptor()
	// collection.DefaultCreatedAt holds the default value on creation for the created_at field.
	collection.DefaultCreatedAt = collectionDescCreatedAt.Default.(func() time.Time)
	// collectionDescUpdatedAt is the schema descriptor for updated_at field.
	collectionDescUpdatedAt := collectionFields[3].Descriptor()
	// collection.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	collection.DefaultUpdatedAt = collectionDescUpdatedAt.Default.(func() time.Time)
	// collection.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	collection.UpdateDefaultUpdatedAt = collectionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// collectionDescID is the schema descriptor for id field.
	collectionDescID := collectionFields[0].Descriptor()
	// collection.DefaultID holds the default value on creation for the id field.
	collection.DefaultID = collectionDescID.Default.(func() uuid.UUID)
	recFields := schema.Rec{}.Fields()
	_ = recFields
	// recDescType is the schema descriptor for type field.
	recDescType := recFields[1].Descriptor()
	// rec.TypeValidator is a validator for the "type" field. It is called by the builders before save.
	rec.TypeValidator = recDescType.Validators[0].(func(string) error)
	// recDescCreatedAt is the schema descriptor for created_at field.
	recDescCreatedAt := recFields[2].Descriptor()
	// rec.DefaultCreatedAt holds the default value on creation for the created_at field.
	rec.DefaultCreatedAt = recDescCreatedAt.Default.(func() time.Time)
	// recDescUpdatedAt is the schema descriptor for updated_at field.
	recDescUpdatedAt := recFields[3].Descriptor()
	// rec.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	rec.DefaultUpdatedAt = recDescUpdatedAt.Default.(func() time.Time)
	// rec.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	rec.UpdateDefaultUpdatedAt = recDescUpdatedAt.UpdateDefault.(func() time.Time)
	// recDescID is the schema descriptor for id field.
	recDescID := recFields[0].Descriptor()
	// rec.DefaultID holds the default value on creation for the id field.
	rec.DefaultID = recDescID.Default.(func() uuid.UUID)
}
