// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Rec is the predicate function for rec builders.
type Rec func(*sql.Selector)

// Representation is the predicate function for representation builders.
type Representation func(*sql.Selector)
